name: run-soapui-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Choix de la distribution Java (temurin fonctionne bien)
          java-version: 11

      - name: Download and install SoapUI
        run: |
          wget https://github.com/hamzanaji123/soapui-ci/releases/download/v1.0/soapUI-light.zip -O soapUI-light.zip
          unzip soapUI-light.zip -d soapui
          chmod +x soapui/bin/soapui.sh

      - name: Run SOAPUI tests
        run: |
          soapui/bin/soapui.sh.sh -s"TestSuite_&" -c"TestCase_&" -r -j -fresults -I -DskipSoapUI=true test-soapui-project.xml

      # Optionnel : sauvegarder les rapports de tests
      #- name: Upload test results
       # uses: actions/upload-artifact@v3
       # with:
         # name: soapui-results
         # path: results

