name: run-soapui-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Download and install SoapUI
        run: |
          wget https://github.com/hamzanaji123/soapui-ci/releases/download/v1.0/soapUI-light.zip -O soapUI-light.zip
          unzip soapUI-light.zip -d soapui
          chmod +x soapui/soapUI-light/bin/testrunner.sh

      - name: Run SOAPUI test - PaymentService / CreatePayment
        run: |
          mkdir -p results
          soapui/soapUI-light/bin/testrunner.sh -s"PaymentService" -c"CreatePayment" -r -j -fresults Stage-soapui-project.xml

  
      #- name: Upload test results
       # uses: actions/upload-artifact@v2
        #with:
          #name: soapui-results
          #path: results
